{"name": "test_empty[hcodes0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert [('00004', 'Д... 4, ...), ...] == []\n  Left contains 26372 more items, first extra item: ('00004', 'Доходная ставка (по грузовым перевозкам)', 'руб./т.', 152, 10, 3, ...)\n  Full diff:\n    [\n  +  ,\n  -  ('00004',\n  -   'Доходная ставка (по грузовым перевозкам)',\n  -   'руб./т.',...\n  \n  ...Full output truncated (448323 lines hidden), use '-vv' to show", "trace": "connection = <cursor object at 0x03B7B128; closed: 0>, hcodes = ('00327', '00131', '00004')\nquery_3_03 = 'create or replace function public.lilo_auto_qa() \\n\\treturns table(\\thcode_id bpchar, hcode_name varchar(300), hcode_....kato_id \\n\\t\\tand a.dir_id = b.dir_id\\ncross join (select * from dm.d_hcode_t where id = %s) hcd\\n    ;\\nend;\\n$f$\\n;'\nquery_3_04 = \"select * from public.lilo_auto_qa()\\nexcept\\nselect  hcode_id, hcode_name, hcode_unit_name, org_id, dor_kod, date_typ...uch_id, nod_id, dir_id, kato_id, vids_id from dm_rep.dm_all_indicators_v\\nwhere hcode_id = %s\\nand calc_rule = 'ratio'\"\n\n    @allure.feature('Расчетные показатели')\n    @allure.story('Полная сверка')\n    @allure.severity('critical')\n    @pytest.mark.parametrize('hcodes',hcodes)\n    def test_empty(connection, hcodes , query_3_03, query_3_04):\n        connection.execute(query_3_03, (hcodes[0], hcodes[1], hcodes[2], hcodes[2]))\n        connection.execute(query_3_04, (hcodes[2],))\n        lines = connection.fetchall()\n        connection.execute('drop function public.lilo_auto_qa();')\n    \n>       assert lines == []\nE       AssertionError: assert [('00004', 'Д... 4, ...), ...] == []\nE         Left contains 26372 more items, first extra item: ('00004', 'Доходная ставка (по грузовым перевозкам)', 'руб./т.', 152, 10, 3, ...)\nE         Full diff:\nE           [\nE         +  ,\nE         -  ('00004',\nE         -   'Доходная ставка (по грузовым перевозкам)',\nE         -   'руб./т.',...\nE         \nE         ...Full output truncated (448323 lines hidden), use '-vv' to show\n\ntest_income.py:42: AssertionError"}, "attachments": [{"name": "stdout", "source": "cc37e4dc-6c50-4dee-977d-e7fafc22ec6a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "hcodes", "value": "('00327', '00131', '00004')"}], "start": 1604502161583, "stop": 1604502206272, "uuid": "132f4f7d-3d29-4eeb-bdc6-62c359dec3b3", "historyId": "3df775e6ded0c57ab5576aba63611005", "testCaseId": "07ce32e44c681d301be8a13e0c006f7d", "fullName": "test_income#test_empty", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Расчетные показатели"}, {"name": "story", "value": "Полная сверка"}, {"name": "suite", "value": "test_income"}, {"name": "host", "value": "62032-nb"}, {"name": "thread", "value": "1768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_income"}]}